### ISSUE TITLE
Make app language and theme depending on system settings, implement Material You

### ISSUE THREAD

**Issue by the4anoni** [marcoXbresciani/TKCompanionApp#16]

**Comment by marcoXbresciani** [comment]
Hello @the4anoni and thanks.

If I'm not mistaken, language and dark/light mode should already follow the device. If not, there's a bug. 😅 In debug mode it seems fine. Could you please give me more details, if any?

What did you mean with Material You? Should I change the overall design?

**Comment by the4anoni** [comment]
> Hello @the4anoni and thanks.
> 
> If I'm not mistaken, language and dark/light mode should already follow the device. If not, there's a bug. 😅 In debug mode it seems fine. Could you please give me more details, if any?
> 
> What did you mean with Material You? Should I change the overall design?

I am using beyond1lte and Android 13. Which details do you need? Log from app? I don't see option to generate log from app.


Yes, material you is new design introduced with Android 12, it went open source with 12L release.

https://material.io/blog/announcing-material-you

**Comment by marcoXbresciani** [comment]
Thanks @the4anoni. Not loss but I was simply trying to understand: if you have dark mode, the app doesn't appear in dark mode? Also, doesn't it appear in your language?

Didn't know about Material You: I'm still on Android 11 so I'm not sure I can manage it here, but I'll try. Do you mind if I split this issue to track language/theme in one issue, and another issue for the new Material You?

**Comment by the4anoni** [comment]
> Thanks @the4anoni. Not loss but I was simply trying to understand: if you have dark mode, the app doesn't appear in dark mode? Also, doesn't it appear in your language?
> 
> Didn't know about Material You: I'm still on Android 11 so I'm not sure I can manage it here, but I'll try. Do you mind if I split this issue to track language/theme in one issue, and another issue for the new Material You?

Yes, I have dark mode enabled, while app by default uses light mode. My phone language is Polish, app by default should be in English, not German.

Yes, if you want to split issue just do it.

**Comment by marcoXbresciani** [comment]
Thanks @the4anoni  I'll check again the mode and language. I'm working on version 4.0.0 (mainly updating libraries) and I'll work on this.

Thank you for helping me improve the app.

**Comment by marcoXbresciani** [comment]
See #17 and #18 for further developments.
