### ISSUE TITLE
Wrong dark/light mode and default language

### ISSUE THREAD

**Issue by marcoXbresciani** [marcoXbresciani/TKCompanionApp#17]
Dark/light mode selection doors not follow current device mode.
Default fallback language must be English instead of German.

_Originally posted by @the4anoni in https://github.com/marcoXbresciani/TKCompanionApp/issues/16#issuecomment-1256925094_

**Comment by marcoXbresciani** [comment]
Basic proposed solution:
- if the device is in dark/light mode, the app will start in the same mode; if the user changes the mode, such mode will be automatically saved and used thereafter (i.e.: if device is in dark mode, app will start in dark mode, but is user switches to light, closing and reopening the app will keep light mode, and viceversa).
- if the device is using an unavailable language, the app will start in English; if the user changes the language, such language will be automatically saved and used thereafter (i.e.: if device is in Japanese, app will start in English, but is user switches to Italian, closing and reopening the app will keep Italian, and so on).

What do you think @the4anoni ?

**Comment by the4anoni** [comment]
> Basic proposed solution:
> 
> * if the device is in dark/light mode, the app will start in the same mode; if the user changes the mode, such mode will be automatically saved and used thereafter (i.e.: if device is in dark mode, app will start in dark mode, but is user switches to light, closing and reopening the app will keep light mode, and viceversa).
> * if the device is using an unavailable language, the app will start in English; if the user changes the language, such language will be automatically saved and used thereafter (i.e.: if device is in Japanese, app will start in English, but is user switches to Italian, closing and reopening the app will keep Italian, and so on).
> 
> What do you think @the4anoni ?

👍
