### ISSUE TITLE
Introduce Material You

### ISSUE THREAD

**Issue by marcoXbresciani** [marcoXbresciani/TKCompanionApp#18]
Introduce Material You design for most modern systems.

_Originally posted by @the4anoni in https://github.com/marcoXbresciani/TKCompanionApp/issues/16#issuecomment-1256922586_

**Comment by marcoXbresciani** [comment]
Waiting for React Native Paper v5 final release.
See [Introducing v5 with Material You](https://callstack.github.io/react-native-paper/introducing-v5-with-material-you.html).
(I'm experimenting locally with v5 release candidates.)

**Comment by marcoXbresciani** [comment]
Hello @the4anoni , I've added Material You from React Native Paper 5.x RC to versions 5.0.0 and 6.0.0 of TKCompanionApp.
As soon as this version 5.x well become final, they'll also add other functionalities from Material You.
What do you think? Is it ok for now?

**Comment by the4anoni** [comment]
> Hello @the4anoni , I've added Material You from React Native Paper 5.x RC to versions 5.0.0 and 6.0.0 of TKCompanionApp. As soon as this version 5.x well become final, they'll also add other functionalities from Material You. What do you think? Is it ok for now?

Yes, It's ok now :)

**Comment by marcoXbresciani** [comment]
Thanks. Closing, then.
