### ISSUE TITLE
Move translation info into the info field

### ISSUE THREAD

**Issue by comradekingu** [marcoXbresciani/TKCompanionApp#9]
https://hosted.weblate.org/contributor-agreement/tkcompanionapp/fastlane/?next=/projects/tkcompanionapp/fastlane/
and
https://hosted.weblate.org/contributor-agreement/tkcompanionapp/i18n/?next=/projects/tkcompanionapp/i18n/
belongs in the info field.

3.2 in https://weblate.org/en/terms/ already covers the licensing.

Representing translators and providing freedback-loops is better facilitated through a [translator-credit field](https://hosted.weblate.org/translate/remmina/remmina/nb_NO/?checksum=deecda9491124d4f) (in the actual app).
Info from there can be copied into the README if needed.

**Comment by marcoXbresciani** [comment]
Thanks!
And thanks for the unexpected Norwegian translation file.

I've spent the afternoon configuring Weblate while attending a boring work meeting, so I'm simply astonished it actually works at all! 😇

Any improvement suggestion is always welcome, thanks.

Tomorrow I'll try taking a look at your suggestion and see what I can do.

**Comment by marcoXbresciani** [comment]
@comradekingu please note that there can be an array of names, for each translation (author field).
All names will be shown as in pictures above.
